
var http = require("http");
var https = require("https");

/**
 * getJSON:  REST get request returning JSON object(s)
 * @param options: http options object
 * @param callback: callback to pass the results JSON object(s) back
 */

exports.getJSON = function(options, onResult) {

    var prot = options.port == 443 ? https : http;
    var req = prot.request(options, function(res) {

        var output = '';
        console.log(options.host + ':' + res.statusCode);
        res.setEncoding('utf8');

        res.on('data', function (chunk) {
            output += chunk;
        });

        res.on('end', function() {
            var obj = JSON.parse(output);
            onResult(res.statusCode, obj);
        });

    });

    req.on('error', function(err) {
        res.send('error: ' + err.message);
    });

    req.end();

};


var mydomain = "http://localhost:3000";
var OAuth = require('oauth').OAuth;
var oa = new OAuth(
  "https://api.twitter.com/oauth/request_token",
  "https://api.twitter.com/oauth/access_token",
  "51eGw6lgyvZBkalaDfzrw",
  "upNoKJ8Ly4KFFij0iRABoMjb1uavdBzjASSrswtGdQ",
  "1.0",
  mydomain + "/search",
  "HMAC-SHA1"
);

// These may be regenerated by Twitter, so check for that if this breaks.
var my_token = '25596212-o396jbBIiiIgGadzXE0G2Gm9OGmGsFKpxf6wVD4k';
var my_secret = 'NRS5Z5mUhy2sdkQkDZerHGGbib0xDe8tROXeGreeZs';


exports.getOptions = function(keyword) {
  
  var auth = oa.authHeader('https://api.twitter.com/1.1/search/tweets.json?q=' + keyword,
                           my_token, my_secret, 'GET');
  return {
    host: 'api.twitter.com',
    port: 443,
    path: '/1.1/search/tweets.json?q=' + keyword,
    method: 'GET',
    headers: {
        'Content-Type': 'application/json',
        'Authorization': auth,
    }
  };

};










